language: php

php:
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - vendor

env:
    global:
        - APP_ENV=test
        - APP_DEBUG=1
        - APP_SECRET=RickAstley
        - DATABASE_URL="mysql://root@127.0.0.1:3306/symfony?charset=utf8mb4&serverVersion=5.7"
        - REDIS_URL="redis://localhost"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist

before_script:
    - bin/console doctrine:database:create

script:
    - composer validate --strict

    - vendor/bin/phpunit || true
    - vendor/bin/behat --strict -vvv --no-interaction
