language: php

php:
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist

before_script:
    - source .env.dist

script:
    - composer validate --strict

    - vendor/bin/phpunit || true
    - vendor/bin/behat --strict -vvv --no-interaction
